- server-api/.env
- server-api/.gitignore
- server-api/package-lock.json
- server-api/package.json
- server-api/prisma/schema.prisma
> db connection completed

- server-api/package-lock.json
- server-api/package.json
- server-api/prisma/schema.prisma
- server-api/src/app.ts
- server-api/src/controllers/auth.ts
- server-api/src/routes/auth.ts
- server-api/src/services/auth.ts
> login and signup enpoint

- client/src/components/Navbar.tsx
- client/src/pages/Login.tsx
- client/src/pages/Signin.tsx
> login and Sigin integrated

- client/package-lock.json
- client/package.json
- client/src/components/JobCard.tsx
- client/src/components/StageColumn.tsx
- client/src/components/Tracker.tsx
- client/src/types.ts
partially implementd
bug fixes are remaing
> drag and drop functionality in Tracker

- server-api/src/app.ts
- server-api/src/controllers/interviews.ts
- server-api/src/routes/interviews.ts
- server-api/src/services/interviews.ts
fetch interview
delete interview
> interviews endpoint created

- client/src/components/InterviewCard.tsx
> delete interview api completed

- client/src/components/InterviewCard.tsx
- client/src/components/Schedule.tsx
> schedule interview integrated

- client/src/components/Profile/AddEducation.tsx
- client/src/components/Profile/EducationProfile.tsx
- client/src/redux/meetApi.ts
- client/src/types.ts
> education functionality added

- client/package-lock.json
- client/package.json
- client/src/pages/Login.tsx
- client/src/pages/Signin.tsx
- client/src/redux/meetApi.ts
- client/src/types.ts
- server-api/prisma/schema.prisma
- server-api/src/services/auth.ts
> google auth added

- server-api/prisma/schema.prisma
- server-api/src/app.ts
- server-api/src/controllers/profile.ts
- server-api/src/routes/profile.ts
- server-api/src/services/profile.ts
get-profile/:username
patch-profile/:username
> crud for profile details

- server-api/prisma/schema.prisma
- server-api/src/controllers/profile.ts
- server-api/src/routes/profile.ts
- server-api/src/services/profile.ts
get-address/:username
patch-address/:username
> profile address crud

- server-api/prisma/schema.prisma
- server-api/src/controllers/profile.ts
- server-api/src/routes/profile.ts
- server-api/src/services/profile.ts
get-"/education/:username"
patch-"/education/:username/:id?"
> profile education crud added

- server-api/prisma/schema.prisma
- server-api/src/controllers/profile.ts
- server-api/src/routes/profile.ts
- server-api/src/services/profile.ts
close #27 
get - "/skills/:username"
patch - "/skills/:username"
> skills endpoint

- server-api/prisma/schema.prisma
- server-api/src/controllers/profile.ts
- server-api/src/routes/profile.ts
- server-api/src/services/profile.ts
get - ("/workexperience/:username")
patch("/workexperience/:username")
> work experience endpoint

- client/package-lock.json
- client/package.json
- client/src/pages/Profile.tsx
- client/src/redux/cloudinaryApi.ts
- client/src/redux/store.ts
> cloudinary setup done

- client/src/components/Profile/AddressProfile.tsx
- client/src/components/Profile/EducationProfile.tsx
- client/src/components/Profile/SkillsProfile.tsx
- client/src/components/Profile/WorkExperienceProfile.tsx
- client/src/main.tsx
- client/src/redux/meetApi.ts
- client/src/types.ts
> integration of address details

- server-api/src/app.ts
- server-api/src/authorizationMiddleware.ts
- server-api/src/controllers/auth.ts
- server-api/src/controllers/interviews.ts
- server-api/src/controllers/profile.ts
- server-api/src/controllers/resources.ts
- server-api/src/controllers/schedule.ts
- server-api/src/globalErrorHandler.ts
- server-api/src/routes/interviews.ts
- server-api/src/routes/profile.ts
- server-api/src/routes/schedule.ts
- server-api/src/services/auth.ts
- server-api/src/services/interviews.ts
- server-api/src/services/profile.ts
- server-api/src/services/resources.ts
- server-api/src/services/schedule.ts
bug fixes
authorization middleware
no need for username in endpoint for all protected routes
> enhancements

- client/src/components/Interview.tsx
- client/src/components/InterviewCard.tsx
- client/src/components/InterviewList.tsx
- client/src/components/Navbar.tsx
- client/src/components/Schedule.tsx
- client/src/redux/interviewsSlice.ts
- client/src/redux/store.ts
toastify on schedule form
ui update on add/delete interview
> interview delete functionality

- server-api/package-lock.json
- server-api/package.json
- server-api/prisma/schema.prisma
> schema update for tracker

- server-api/prisma/schema.prisma
- server-api/src/app.ts
- server-api/src/controllers/tracker.ts
- server-api/src/routes/tracker.ts
- server-api/src/services/tracker.ts
crud endpoints are all created and tested
> tracker api crud created

- client/src/components/Schedule.tsx
- client/src/components/Tracker/AddJob.tsx
- client/src/components/Tracker/Tracker.tsx
- client/src/pages/Login.tsx
- client/src/pages/Signin.tsx
Issue #149 is resolved
Fixed - Save button disabled Issue on Dashboard Page
> Solving issue #149 button disabled

- client/src/components/Schedule.tsx
- client/src/components/Tracker/AddJob.tsx
- client/src/components/Tracker/Tracker.tsx
- client/src/pages/Login.tsx
- client/src/pages/Signin.tsx
Reverts 609harsh/Meetconnect#151
> Revert "Solving issue #149 button disabled"

- client/src/components/Schedule.tsx
- client/src/components/Tracker/AddJob.tsx
- client/src/components/Tracker/Tracker.tsx
- client/src/pages/Login.tsx
- client/src/pages/Signin.tsx
The feature of disabling the button has successfully been implemented
> Issue #149 Disabling the button
